version: '3.8'

services:
  ride-payment-service:
    build: .
    container_name: ride-payment-service_v1
    ports:
      - "8081:8081"  # Expose the Spring Boot app on port 8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - h2-data:/data  # Persist H2 database data
    networks:
      - ride_network

volumes:
  h2-data:  # A volume to persist data for H2 database
    driver: local

networks:
  ride_network:
    driver: bridge
