apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-container
        image: img-location-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
